### ISSUE TITLE
Delay when searching

### ISSUE THREAD

**Issue by ajostergaard** [sylouuu/chrome-open-tabs#1]
Great extension - thanks!!!

Minor quibble, when I start typing in the 'search in title' box there's always a small freeze up while the browser iterates through all my tabs.

Is it possible to filter asynchronously? By that I mean, do the filtering in a thread such that the UI isn't blocked.

**Comment by dkline03** [comment]
I updated background.js, options.js, and options.html so that the tabs are tracked by the background script instead of being newly loaded when opening options.html. It has definitely made the delay a lot shorter.

How should I submit these changes?

**Comment by ajostergaard** [comment]
@dkline03 thanks! If we're lucky @sylouuu will respond to a PR...

**Comment by sylouuu** [comment]
Hi @ajostergaard & @dkline03 

Sorry for the delay, it seems I didn't watch my own repository so I didn't receive the notifications until I got mentioned by @ajostergaard.

About the topic, @ajostergaard, when you start typing in search box, there is no live iterations. Listed tabs are live refreshed, the search computing is made by Angular itself on this standard Javascript object. You may experience a freeze if you so many tabs?

@dkline03 I'm not sure if your changes are related to this topic but you can find on the Web how to contribute on GitHub, check this [guide](https://help.github.com/articles/creating-a-pull-request/) or browse the GitHub Help Center.

Best
