### ISSUE TITLE
Custom icon not being displayed

### ISSUE THREAD

**Issue by jameshume** [sylouuu/chrome-open-tabs#10]
Hi,

Excellent app! Just started using it.

The inbuilt icons work fine but the custom images don't appear to.

I am using Version 77.0.3865.90 (Official Build) (64-bit)

I can see the icon gets "loaded" or at least can be seen by the app:

![image](https://user-images.githubusercontent.com/3994844/66582576-eeb63700-eb79-11e9-80b9-94264dcd92cf.png)

But in the tabs I see this:

![image](https://user-images.githubusercontent.com/3994844/66582667-0beb0580-eb7a-11e9-83c8-b24cda017b52.png)

The other tab functions are working - the tab will be made unique and protected which is great... the icon doesn't change. Small thing but would be nice.

Img URL I'm using is this: https://upload.wikimedia.org/wikipedia/commons/0/09/Blue_computer_icon.svg

Thanks!

**Comment by jameshume** [comment]
Darn... it was coz it was SVG... sorry!

**Comment by sylouuu** [comment]
It was not the right repository to post an issue btw. ;)
