### ISSUE TITLE
Go to - button doesn't work

### ISSUE THREAD

**Issue by ernstgal** [sylouuu/chrome-open-tabs#2]
In the overview of open tabs the "Go to" -button (arrow) doesn't work, if the tab is in an **other** window!

Versionsinformation:
Version:	44.0.2510.1449 (PGO) - Opera ist auf dem neuesten Stand
Update-Stream:	Stable
Betriebssystem:	Windows 7 64-bit

Browser-Identifikation:
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36 OPR/44.0.2510.1449

**Comment by dkline03** [comment]
In options.js, the use of the following will fix this issue:

```
$scope.goToTab = function (tab) {
	chrome.tabs.update(tab.id, { active: true, highlighted: true }, function(_tab){
		chrome.windows.update(_tab.windowId,{focused:true});
	});
};
```
I love this extension! Thanks for the awesome work!!!

**Comment by sylouuu** [comment]
Hi @ernstgal 

Sorry for the delay, it seems I didn't watch my own repository so I didn't receive the notifications until I got mentioned in the previous issue.

I'll check this bug later, thank's for reporting this!

Best

**Comment by sylouuu** [comment]
Thank you guys, version 0.3.1 has been published and will spread in few hours.

Best

**Comment by ernstgal** [comment]
Hi sylouuu, your new build works fine. thx
