### ISSUE TITLE
The "open tabs" tab is not displayed in the foreground.

### ISSUE THREAD

**Issue by ernstgal** [sylouuu/chrome-open-tabs#4]
If the "open tabs" tab is already open in a background window, it is not displayed in the foreground, if you push the button in the toolbar.

**Comment by sylouuu** [comment]
Hi @ernstgal,

I just reproduced this behavior.

1. Click on "Open Tabs" icon
2. Open new Chrome window
3. Click on "Open Tabs" icon from new window => nothing happens

After a fix:

1. Click on "Open Tabs" icon
2. Open new Chrome window
3. Click on "Open Tabs" icon from new window => focus "Open Tabs" in previous window

Is that correct for you?

Best

**Comment by sylouuu** [comment]
Done in 0.3.2.

**Comment by ernstgal** [comment]
Hi sylouuu, your new build works fine. thx
