### ISSUE TITLE
Promising start for this extensions - where could it go to?

### ISSUE THREAD

**Issue by EC-O-DE** [sylouuu/chrome-open-tabs#5]
Good start for this extension. Those who are "lost in tabs" will find this useful. Hopefully this is the bare bones and the extension will grow and advance as more possibilities comes available.
Could there be possibility to run extension as floating panel on the right side of the screen? Optionally to a tab?

Hmmm there could be a dark theme as option.

Just throwing some ideas!

Opera is an 'amazing' browser - but what's still missing is that sophisticated tab stacking -feature of Opera 12. Vivaldi has a nice tab grouping -feature that's roughly the same as was in Opera 12. Dunno if it would be able to go towards those by extension, this or some other extension.

**Comment by sylouuu** [comment]
Hello @ZenFi,

Thanks for your feedback. I'm sorry but I don't have any plan for Open Tabs at the moment.

Bests
