### ISSUE TITLE
Hiding a tab?

### ISSUE THREAD

**Issue by EC-O-DE** [sylouuu/chrome-open-tabs#6]
Does hiding a tab conserve RAM?
Similar to such as "Great suspender" and "Tab Suspender"?

Is there any benefit hiding a tab with this ext other than it's hidden?

Could you add powerful RAM conservation?

**Comment by sylouuu** [comment]
Hi @EC-O-DE,

As you must know, on Chrome, each tab is a separate process, so a tab consumes RAM and processor.

When you hide a tab with Open Tabs, the URL is saved somewhere on your computer (localStorage) and the tab is **removed**. So the benefit is real, the tab doesn't exist anymore.

Hope this is clear.

Best

**Comment by EC-O-DE** [comment]
Ok, thanks for clarifying, I wasn't sure what the underlying method u had for hiding a tab. Thanks.

**Comment by EC-O-DE** [comment]
It seems that the whole ext unloads from memory when it's not needed - albeit still being active.
