### ISSUE TITLE
Custom Tabs

### ISSUE THREAD

**Issue by meman887** [sylouuu/chrome-open-tabs#9]
Not really an issue but a suggestion, it would be nice if you could add an option to create custom Tab menu and name it.

**Comment by sylouuu** [comment]
Hello,

What's the point? It's quicker to open a new tab and go to an URL.

Best

**Comment by meman887** [comment]
>What's the point? It's quicker to open a new tab and go to an URL.

Well the point is so people can create a custom list i.e. "Later" {to come back to it later i.e. temporary place to store URL's, instead of having to Bookmark them). Or for a "Shopping list" i.e Category.

Also would be nice if you could save a backup in case something goes wrong with the Browser, if someone had to reinstall it.

**Comment by sylouuu** [comment]
Well, a folder in Bookmarks does the same job, as you said. With all features, such as sync.
